### ISSUE TITLE
feature request: request voice node

### ISSUE THREAD

**Issue by kraiz** [gausma/nodered-contrib-signal-client#1]
Amazing project. Really nice documentation. I was stunned when I saw that you created this project just 2 days ago. That's a really nice way to have push notifications out of NodeRed. Even chatbots are possible 👍

I'm trying to register a fixed line number where I can't receive an sms. I saw the library supports voice verification (https://github.com/gausma/libsignal-service-javascript/blob/a197c985628694a66c151b4ffa0a2ec20de45f2b/src/AccountManager.js#L45). Am I correct that it shouldn't be much more then a copy of `RequestSMSNode` (maybe `RequestVoiceNode`) with this line (https://github.com/gausma/nodered-contrib-signal-client/blob/64ac5a3303f603a83b18e39df8670fb74ca3cff1/src/signal-client.js#L57) changed to `requestVoiceVerification()`?

I just started with using NodeRed 5 days ago but I'm willing to provide a PR if you would accept.

**Comment by gausma** [comment]
Thanks for that suggestion. In fact, it was already prepared. You'll find the requested functionality in version 1.2.0.
https://www.npmjs.com/package/nodered-contrib-signal-client/v/1.2.0
