### ISSUE TITLE
Sending and receiving failure

### ISSUE THREAD

**Issue by MichaelAnders** [gausma/nodered-contrib-signal-client#17]
I've been able to register a number with Signal with a separate landline number - at least the registration was successful. I do not get any notification in Signal though that my "contact" is now using Signal (not sure if that just takes time?)

However, I can neither send nor receive messages. It makes no difference if I use "non-live" mode or "live" mode.

I set up a simple node that sends to the same number as receiver - I also tried your example for a simple send/receive node with my own account and my number.

I press "send" and nothing happens on the receiving node. There is also no error message.

Now I'm not sure where the problem is... 
Some questions from my side:
1 - Does that mean that Signal servers were actually contacted and they replied successful delivery?
2 - Is there a check if the receiver was started properly and is "waiting" for messages?
3 - Shouldn't I get some notification on my mobile phone that my contact with the used landline number now is on Signal?

I'm running Debian Buster on x64.

**Comment by gausma** [comment]
Did you check your Node-RED logs? If there are problems you'll get log entries. Have al look into the  "Debug messages" sidebar.
Or activate the "Verbose Logging" in the send and receive nodes. and see detailed messages in the Node-RED logs:
https://discourse.nodered.org/t/where-can-i-read-node-red-logs/7698/6

**Comment by MichaelAnders** [comment]
My bad, I added some debug output to one of the JS files and that broke it... Now it works perfectly - amazing stuff!!!
