### ISSUE TITLE
not able to activate a landline number

### ISSUE THREAD

**Issue by Andy2020-DE** [gausma/nodered-contrib-signal-client#21]
Hello all

I am not able to activate a landline number for the Signal Node in RedMatic version 7.2.1.

If I use "request-voice" and enter the landline number, the debugging also shows "Signal client: registration code requested via voice call", but no call is received. If I enter a cell phone number in "request-voice", I get an SMS (shouldn't there also be a voice call?).

If I enter the landline number on a mobile, a call comes and I can activate the landline number on the mobile.

An update of nodered-contrib-signal-client from 2.4.0 to 2.4.1 is unfortunately also not possible.

**Comment by chonki** [comment]
I have the same issue

**Comment by qroac** [comment]
Same here with a landline number from Germany.

Sending a request-voice with captcha code I get response:
"Signal client: registration code requested via voice call."

But the call never comes.
I tried at least 15 times at different times of day since yesterday morning.

fresh node-red install, less than a week old.
- node-red 1.2.9
- nodered-contrib-signal-client 2.4.1

**Comment by max3232rs** [comment]
Hi all, metoo ;-)

I've found out, that in WebAPI.js*, the url for sms and voice is identical - sms in both cases.
I changed it to /voice/code/.... and it worked again.
This is my full line:
urlParameters = `/voice/code/${number}?Accept-Language=de&captcha=${captcha}`;
I 've added the "Accept-Language" to get the call in german. (optional premium feature, off topic here)

@gausma Is it possible that you copy/pasted too much from requestVerificationSMS to requestVerificationVoice within your last commit? I think, it was ok before.

https://github.com/gausma/libsignal-service-javascript/commit/78c0378e8710bb7613e2c5de8a999c32c100d487#diff-281de3dbdba9c61ca257e9edb0969333673c6d305c6f8413287a355f87bc4101

*)@gausma/libsignal-service-javascript/src/WebAPI.js

Cheers

**Comment by mmuller88** [comment]
@gausma Why just closed? I do have the same problem. I will try update Node ...
