### ISSUE TITLE
Registration performed but send message error

### ISSUE THREAD

**Issue by dedynobre** [gausma/nodered-contrib-signal-client#4]
I did the setup and it's okay.
But when I send the message as an example it returns an error:

![image](https://user-images.githubusercontent.com/8119694/104504370-1ab43980-55c1-11eb-8263-56d5efcb3297.png)

**Comment by hjboven** [comment]
Hello dedynobre,

I had the same problem and the Page could do with some more explanation and examples.

My Injectionbutton does not throw an error anymore yet I do not seem to be able to deliver the message to my account on my handy. 

[{"id":"68a565f.e52479c","type":"inject","z":"adf273b.803ae9","name":"","props":[{"p":"payload.content","v":"Hello","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":1010,"y":580,"wires":[["238e5bce.5b5144","94ea0885.18ec18"]]}]

**Comment by MarkBorr** [comment]
Hello!
I had the same issue. Sending the registrationcode with a "-" between the first and second three numbers solved the problem for me. So you should try typing the registration code in the format xxx-xxx. Hope this helps.

**Comment by hjboven** [comment]
My registration worked alright it reports. 
<img width="205" alt="1" src="https://user-images.githubusercontent.com/38787048/104614514-9dec9280-5688-11eb-9062-f2172a0ff795.png">

Yet sending altough it reports to be ok does not deliver anything on my handy
<img width="203" alt="2" src="https://user-images.githubusercontent.com/38787048/104614646-b9579d80-5688-11eb-92dc-fd8d451a38db.png">

**Comment by gausma** [comment]
Did you active the flag "Live Server" in your account before registration? Only a "Live Server" account can communicate with the client on your cell phone.

For safety, a Signal staging server (testing server) can be used  while you carry out your experiments. This means that it will only send and receive messages from other clients using the staging server!

I've improved the error messages in version 2.0.2

**Comment by sztof** [comment]
> 
> 
> My registration worked alright it reports.
> <img alt="1" width="205" src="https://user-images.githubusercontent.com/38787048/104614514-9dec9280-5688-11eb-9062-f2172a0ff795.png">
> 
> Yet sending altough it doesn not seem to give an Error does not deliver anything on my handy
> <img alt="2" width="203" src="https://user-images.githubusercontent.com/38787048/104614646-b9579d80-5688-11eb-92dc-fd8d451a38db.png">
Please upgrade the signal messenger package, after that you'll see more information in debug info.

After succesfull registration I'm trying to send a message and error occurs
payload: "Signal client error: {"successfulIdentifiers":[],"failoverIdentifiers":[],"errors":[{"name":"UnregisteredUserError","identifier":"+48XXXXXXXXX","code":404,"reason":"Failed to retrieve new device keys for number +48XXXXXXXXX"}],"unidentifiedDeliveries":[],"dataMessage":{"type":"Buffer","data":[50,6,225,171,225,144,135,180,56,221,141,155,169,240,46]}}"

+48XXXXXXXXX is a registered number in signal communicator.

**Comment by giddyhup** [comment]
Since I am running into the same issues and I think the documentation does not specifically state this: is the registration similar to adding an additional device to an already existing account or is it for a new primary account (a previously unregistered phone number)?

**Comment by hjboven** [comment]
Hi Giddyhup, It's an new primary Account so you need a new previously unregistred number.  I fell into the same trap and took a while to figure it out.
